language: node_js

node_js:
  - stable
  
install:
  - npm install
  - npm install -g codecov

script:
  - npm run build-dev
  - npm run build-prod
  - npm test
  - jest ./test/reAxios.spec.js 
  - codecov
